global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth:8013']

  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway:8012']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']