global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['a4-auth:8013']

  - job_name: 'gateway-service'
    static_configs:
      - targets: ['a4-gateway:8012']
