app:
  host: 0.0.0.0
  port: 5000
  secret: secret
db:
  host: 127.0.0.1
  port: 8050
  user: postgres
  password: postgresql
  name: a4code_db
  sslmode: "disable"
minio:
  host: 127.0.0.1
  port: 9000
  user: minio
  password: miniominio
  bucket_name: "avatars"
  endpoint: 127.0.0.1:9000
  use_ssl: false
  public_endpoint: flintmail.ru
  public_use_ssl: true
