app:
  host: 0.0.0.0
  auth_port: 8001
  messages_port: 8002
  profile_port: 8003
  gateway_port: 8000
  metrics_port: 8005
  secret: secret
db:
  host: 127.0.0.1
  port: 8004
  user: postgres
  password: postgresql
  name: a4code_db
  sslmode: "disable"
minio:
  host: 127.0.0.1
  port: 8005
  user: minio
  password: miniominio
  bucket_name: "avatars"
  endpoint: 127.0.0.1:8005
  use_ssl: false
  public_endpoint: flintmail.ru
  public_use_ssl: true
